# Фреймворк PyTorch для разработки искусственных нейронных сетей
## Урок 1. Основные понятия и структуры PyTorch
- Создайте случайный FloatTensor размера 3x4x5
- Выведите его форму (shape)
- Приведите его к форме 6х10
- Создайте случайный IntTensor размера 10
- Умножьте созданный FloatTensor на созданный IntTensor поэлементно
- Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
- Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
- Создайте единичный тензор размера 5x6
- Переведите его в формат numpy

In [29]:
import torch


In [30]:
x = torch.randn(3,4,5) .type(torch.FloatTensor)  # Создайте случайный FloatTensor размера 3x4x5
print(x)

tensor([[[ 1.7430e-02,  3.2295e-02, -1.3049e+00,  3.2691e-02, -2.3763e+00],
         [-3.0196e-01, -2.6929e+00,  4.4646e-01, -4.9403e-01, -9.0802e-01],
         [-1.0767e+00,  6.7379e-01, -3.3650e-01,  3.6944e-01, -1.1745e+00],
         [ 6.1508e-02, -6.6485e-01, -2.3708e+00, -3.4975e-01,  6.3568e-01]],

        [[-8.0594e-01,  6.4620e-01, -2.5192e+00, -7.1666e-01, -8.9143e-02],
         [-2.3762e+00,  7.8317e-01,  1.1452e-01,  2.2016e-01,  3.2615e-02],
         [-1.4007e-01, -1.3028e+00,  1.1593e+00,  9.6611e-01,  1.1913e+00],
         [-5.9405e-01,  9.6214e-01, -2.0104e+00, -1.8346e-02, -3.4504e-02]],

        [[ 1.7456e+00,  5.5001e-01, -5.0547e-01, -3.9931e-01, -1.6277e+00],
         [-1.4260e+00,  1.0174e+00,  1.4492e-03, -7.4670e-01,  2.1880e-01],
         [ 3.6804e-01,  1.3300e+00, -6.4630e-03, -1.4612e+00, -8.2727e-01],
         [-8.1831e-01, -5.0414e-01,  2.4397e+00,  1.2448e+00, -2.0181e-01]]])


In [50]:
x.shape #Выведите его форму (shape)

torch.Size([3, 4, 5])

In [51]:
z = x.view(6, 10)  # Приведите его к форме 6х10
z

tensor([[ 1.7430e-02,  3.2295e-02, -1.3049e+00,  3.2691e-02, -2.3763e+00,
         -3.0196e-01, -2.6929e+00,  4.4646e-01, -4.9403e-01, -9.0802e-01],
        [-1.0767e+00,  6.7379e-01, -3.3650e-01,  3.6944e-01, -1.1745e+00,
          6.1508e-02, -6.6485e-01, -2.3708e+00, -3.4975e-01,  6.3568e-01],
        [-8.0594e-01,  6.4620e-01, -2.5192e+00, -7.1666e-01, -8.9143e-02,
         -2.3762e+00,  7.8317e-01,  1.1452e-01,  2.2016e-01,  3.2615e-02],
        [-1.4007e-01, -1.3028e+00,  1.1593e+00,  9.6611e-01,  1.1913e+00,
         -5.9405e-01,  9.6214e-01, -2.0104e+00, -1.8346e-02, -3.4504e-02],
        [ 1.7456e+00,  5.5001e-01, -5.0547e-01, -3.9931e-01, -1.6277e+00,
         -1.4260e+00,  1.0174e+00,  1.4492e-03, -7.4670e-01,  2.1880e-01],
        [ 3.6804e-01,  1.3300e+00, -6.4630e-03, -1.4612e+00, -8.2727e-01,
         -8.1831e-01, -5.0414e-01,  2.4397e+00,  1.2448e+00, -2.0181e-01]])

In [32]:
v = torch.randperm(10) #Создайте случайный IntTensor размера 10
v

tensor([0, 9, 8, 4, 6, 1, 5, 3, 2, 7])

In [37]:
r = torch.mul(z,v) #Умножьте созданный FloatTensor на созданный IntTensor поэлементно
r

tensor([[ 0.0000e+00,  2.9065e-01, -1.0439e+01,  1.3076e-01, -1.4258e+01,
         -3.0196e-01, -1.3465e+01,  1.3394e+00, -9.8805e-01, -6.3561e+00],
        [-0.0000e+00,  6.0641e+00, -2.6920e+00,  1.4778e+00, -7.0470e+00,
          6.1508e-02, -3.3243e+00, -7.1125e+00, -6.9951e-01,  4.4497e+00],
        [-0.0000e+00,  5.8158e+00, -2.0154e+01, -2.8667e+00, -5.3486e-01,
         -2.3762e+00,  3.9158e+00,  3.4357e-01,  4.4032e-01,  2.2830e-01],
        [-0.0000e+00, -1.1725e+01,  9.2744e+00,  3.8645e+00,  7.1479e+00,
         -5.9405e-01,  4.8107e+00, -6.0311e+00, -3.6693e-02, -2.4153e-01],
        [ 0.0000e+00,  4.9501e+00, -4.0438e+00, -1.5972e+00, -9.7660e+00,
         -1.4260e+00,  5.0870e+00,  4.3476e-03, -1.4934e+00,  1.5316e+00],
        [ 0.0000e+00,  1.1970e+01, -5.1704e-02, -5.8450e+00, -4.9636e+00,
         -8.1831e-01, -2.5207e+00,  7.3192e+00,  2.4897e+00, -1.4127e+00]])

In [49]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

g = torch.mul(r,r)
g

tensor([[0.0000e+00, 8.4479e-02, 1.0898e+02, 1.7099e-02, 2.0329e+02, 9.1178e-02,
         1.8130e+02, 1.7939e+00, 9.7624e-01, 4.0401e+01],
        [0.0000e+00, 3.6773e+01, 7.2470e+00, 2.1838e+00, 4.9661e+01, 3.7832e-03,
         1.1051e+01, 5.0587e+01, 4.8931e-01, 1.9800e+01],
        [0.0000e+00, 3.3824e+01, 4.0618e+02, 8.2177e+00, 2.8607e-01, 5.6465e+00,
         1.5334e+01, 1.1804e-01, 1.9389e-01, 5.2122e-02],
        [0.0000e+00, 1.3747e+02, 8.6014e+01, 1.4934e+01, 5.1093e+01, 3.5290e-01,
         2.3143e+01, 3.6374e+01, 1.3463e-03, 5.8337e-02],
        [0.0000e+00, 2.4503e+01, 1.6352e+01, 2.5512e+00, 9.5374e+01, 2.0335e+00,
         2.5877e+01, 1.8902e-05, 2.2302e+00, 2.3457e+00],
        [0.0000e+00, 1.4328e+02, 2.6733e-03, 3.4164e+01, 2.4637e+01, 6.6963e-01,
         6.3539e+00, 5.3571e+01, 6.1985e+00, 1.9957e+00]])

In [1]:
#  Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

import torch

x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = x**3 + z - 75*t

y.backward()

print('Производная по x:', x.grad)
print('Производная по z:', z.grad)
print('Производная по t:', t.grad)

Производная по x: tensor(3.)
Производная по z: tensor(1.)
Производная по t: tensor(-75.)


In [2]:
# Создайте единичный тензор размера 5x6
tensor = torch.ones(5, 6)
print(tensor)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [3]:
# Переведите его в формат numpy
import numpy as np

numpy_array = tensor.numpy()
print(numpy_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
